version: "3.4"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:connect=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=root;
    ports:
      - "8081:80"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"
   

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:80"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=agoravaicaralho
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./cria_transacao.sql:/docker-entrypoint-initdb.d/cria_transacao.sql
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "310MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
